/**
 * NEXUS SCHOLAR — Database Seed
 * Populates the database with 6 verified known scholarships.
 * Run: npm run seed   OR   npx ts-node prisma/seed.ts
 */
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const SEED_SCHOLARSHIPS = [
  {
    name: 'Türkiye Bursları',
    slug: 'turkiye-burslari',
    shortName: 'TB',
    hostUniversity: 'Various Turkish Universities (100+ options)',
    hostCountry: 'Turkey',
    hostCountryCode: 'TR',
    degreeLevel: ['bachelor'],
    fieldsOfStudy: ['cs', 'software_engineering', 'cybersecurity', 'ai', 'it'],
    csRelevant: true,
    csRelevanceScore: 14,
    fundingType: 'FULLY_FUNDED' as const,
    coversTuition: true,
    coversAccommodation: true,
    coversStipend: true,
    coversAirfare: true,
    coversHealthInsurance: true,
    monthlyStipendAmount: 70,
    monthlyStipendCurrency: 'USD',
    tuitionCoveragePct: 100,
    requiresIelts: false,
    requiresToefl: false,
    acceptsMoi: true,
    acceptsEnglishCert: true,
    eligibleNationalities: ['PK', 'BD', 'NG', 'EG', 'MA', 'OPEN'],
    applicationDeadline: new Date('2026-02-20'),
    applicationOpenDate: new Date('2025-12-01'),
    cycleFrequency: 'annual',
    officialSourceUrl: 'https://www.turkiyeburslari.gov.tr',
    applicationUrl: 'https://tbbs.meb.gov.tr',
    tier: 'ALPHA',
    competitivenessLevel: 'extremely_high',
    estimatedAwards: 5000,
    dataConfidenceScore: 95,
    suitabilityScore: 96,
    verificationStatus: 'VERIFIED' as const,
    status: 'ACTIVE' as const,
    isPublished: true,
    featured: true,
    ieltsNote: 'No IELTS required. Turkish language preparatory year + English programs available.',
    keyBenefit: 'Tuition + accommodation + health insurance + return airfare + Turkish language course',
  },
  {
    name: 'China Government Scholarship (CSC)',
    slug: 'china-csc-scholarship',
    shortName: 'CSC',
    hostUniversity: 'Tsinghua, Zhejiang, BUPT, USTC and 50+ more',
    hostCountry: 'China',
    hostCountryCode: 'CN',
    degreeLevel: ['bachelor'],
    fieldsOfStudy: ['cs', 'ai', 'data_science', 'software_engineering', 'cybersecurity'],
    csRelevant: true,
    csRelevanceScore: 15,
    fundingType: 'FULLY_FUNDED' as const,
    coversTuition: true,
    coversAccommodation: true,
    coversStipend: true,
    coversAirfare: true,
    coversHealthInsurance: true,
    monthlyStipendAmount: 345,
    monthlyStipendCurrency: 'USD',
    tuitionCoveragePct: 100,
    requiresIelts: false,
    requiresToefl: false,
    acceptsMoi: true,
    acceptsEnglishCert: true,
    eligibleNationalities: ['PK', 'OPEN'],
    applicationDeadline: new Date('2026-03-31'),
    applicationOpenDate: new Date('2025-12-01'),
    cycleFrequency: 'annual',
    officialSourceUrl: 'https://www.csc.edu.cn/laihua',
    applicationUrl: 'https://www.campuschina.org',
    tier: 'ALPHA',
    competitivenessLevel: 'high',
    estimatedAwards: 50000,
    dataConfidenceScore: 92,
    suitabilityScore: 92,
    verificationStatus: 'VERIFIED' as const,
    status: 'ACTIVE' as const,
    isPublished: true,
    featured: true,
  },
  {
    name: 'Stipendium Hungaricum',
    slug: 'stipendium-hungaricum',
    shortName: 'SH',
    hostUniversity: '28 Hungarian Public Universities (ELTE, BME, Debrecen, Pécs...)',
    hostCountry: 'Hungary',
    hostCountryCode: 'HU',
    degreeLevel: ['bachelor'],
    fieldsOfStudy: ['cs', 'software_engineering', 'it', 'informatics', 'data_science'],
    csRelevant: true,
    csRelevanceScore: 13,
    fundingType: 'FULLY_FUNDED' as const,
    coversTuition: true,
    coversAccommodation: true,
    coversStipend: true,
    coversAirfare: false,
    coversHealthInsurance: true,
    monthlyStipendAmount: 120,
    monthlyStipendCurrency: 'USD',
    tuitionCoveragePct: 100,
    requiresIelts: false,
    requiresToefl: false,
    acceptsMoi: true,
    acceptsEnglishCert: true,
    acceptsIeltsWaiver: true,
    eligibleNationalities: ['PK', 'OPEN'],
    applicationDeadline: new Date('2026-01-15'),
    applicationOpenDate: new Date('2025-11-01'),
    cycleFrequency: 'annual',
    officialSourceUrl: 'https://stipendiumhungaricum.hu',
    applicationUrl: 'https://apply.stipendiumhungaricum.hu',
    tier: 'ALPHA',
    competitivenessLevel: 'medium',
    estimatedAwards: 5000,
    dataConfidenceScore: 91,
    suitabilityScore: 90,
    verificationStatus: 'VERIFIED' as const,
    status: 'ACTIVE' as const,
    isPublished: true,
    featured: true,
  },
  {
    name: 'Korean Government Scholarship (KGSP/GKS)',
    slug: 'kgsp-korea',
    shortName: 'KGSP',
    hostUniversity: 'KAIST, Yonsei, Korea University, Sungkyunkwan + 57 more',
    hostCountry: 'South Korea',
    hostCountryCode: 'KR',
    degreeLevel: ['bachelor'],
    fieldsOfStudy: ['cs', 'software_engineering', 'ai', 'cybersecurity', 'computer_engineering'],
    csRelevant: true,
    csRelevanceScore: 14,
    fundingType: 'FULLY_FUNDED' as const,
    coversTuition: true,
    coversAccommodation: true,
    coversStipend: true,
    coversAirfare: true,
    coversHealthInsurance: true,
    monthlyStipendAmount: 680,
    monthlyStipendCurrency: 'USD',
    tuitionCoveragePct: 100,
    requiresIelts: false,
    requiresToefl: false,
    acceptsMoi: false,
    acceptsEnglishCert: true,
    eligibleNationalities: ['PK', 'OPEN'],
    applicationDeadline: new Date('2026-03-10'),
    applicationOpenDate: new Date('2026-01-01'),
    cycleFrequency: 'annual',
    officialSourceUrl: 'https://www.studyinkorea.go.kr/en/sub/gks/allnew_gks_u.do',
    tier: 'ALPHA',
    competitivenessLevel: 'extremely_high',
    estimatedAwards: 1000,
    dataConfidenceScore: 89,
    suitabilityScore: 88,
    verificationStatus: 'VERIFIED' as const,
    status: 'ACTIVE' as const,
    isPublished: true,
    featured: false,
  },
  {
    name: 'Malaysian International Scholarship (MIS)',
    slug: 'mis-malaysia',
    shortName: 'MIS',
    hostUniversity: 'UTM, UPM, UM, UKM, USM, UiTM + more',
    hostCountry: 'Malaysia',
    hostCountryCode: 'MY',
    degreeLevel: ['bachelor'],
    fieldsOfStudy: ['cs', 'it', 'software_engineering', 'data_science'],
    csRelevant: true,
    csRelevanceScore: 12,
    fundingType: 'FULLY_FUNDED' as const,
    coversTuition: true,
    coversAccommodation: true,
    coversStipend: true,
    coversAirfare: true,
    coversHealthInsurance: false,
    monthlyStipendAmount: 320,
    monthlyStipendCurrency: 'USD',
    tuitionCoveragePct: 100,
    requiresIelts: false,
    requiresToefl: false,
    acceptsMoi: true,
    acceptsEnglishCert: true,
    eligibleNationalities: ['PK', 'OPEN'],
    applicationDeadline: new Date('2026-04-30'),
    applicationOpenDate: new Date('2026-01-01'),
    cycleFrequency: 'annual',
    officialSourceUrl: 'https://biasiswa.mohe.gov.my/INTER/',
    tier: 'ALPHA',
    competitivenessLevel: 'medium',
    dataConfidenceScore: 84,
    suitabilityScore: 85,
    verificationStatus: 'VERIFIED' as const,
    status: 'ACTIVE' as const,
    isPublished: true,
    featured: false,
  },
  {
    name: 'Poland NAWA Scholarship',
    slug: 'poland-nawa',
    shortName: 'NAWA',
    hostUniversity: 'Warsaw, AGH Kraków, Wrocław University of Technology + more',
    hostCountry: 'Poland',
    hostCountryCode: 'PL',
    degreeLevel: ['bachelor'],
    fieldsOfStudy: ['cs', 'cybersecurity', 'it', 'software_engineering', 'mathematics'],
    csRelevant: true,
    csRelevanceScore: 11,
    fundingType: 'TUITION_STIPEND' as const,
    coversTuition: true,
    coversAccommodation: true,
    coversStipend: true,
    coversAirfare: false,
    coversHealthInsurance: false,
    monthlyStipendAmount: 320,
    monthlyStipendCurrency: 'USD',
    tuitionCoveragePct: 100,
    requiresIelts: false,
    requiresToefl: false,
    acceptsMoi: true,
    acceptsEnglishCert: true,
    eligibleNationalities: ['PK', 'OPEN'],
    applicationDeadline: new Date('2026-05-31'),
    applicationOpenDate: new Date('2026-02-01'),
    cycleFrequency: 'annual',
    officialSourceUrl: 'https://nawa.gov.pl/en/programmes/students',
    tier: 'BETA',
    competitivenessLevel: 'low',
    dataConfidenceScore: 80,
    suitabilityScore: 82,
    verificationStatus: 'VERIFIED' as const,
    status: 'ACTIVE' as const,
    isPublished: true,
    featured: false,
  },
];

async function main() {
  console.log('🌱 Seeding NEXUS SCHOLAR database...');

  for (const data of SEED_SCHOLARSHIPS) {
    await prisma.scholarship.upsert({
      where: { slug: data.slug },
      update: data,
      create: data,
    });
    console.log(`  ✓ ${data.name}`);
  }

  console.log(`\n✅ Seeded ${SEED_SCHOLARSHIPS.length} scholarships successfully.`);
}

main()
  .catch(e => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
